default:
  image: registry.csc.sibsutis.ru/trpo/ci

stages:
  - check-codestyle
  - build
  - test

.build-script:
  script:
    - echo "Compiling the code..."
    - make -mwindows
    - echo "Compile complete."

.check-codestyle:
  script:
    - echo "Check codestyle..."
    - git ls-files *.cpp *.h | xargs clang-format -i --verbose && git diff --exit-code
    - echo "Codestyle is fine."

.test-script:
 script:
    - echo "Compiling the code..."
    - make test -mwindows
    - echo "Compile complete."

checkstyle:
  stage: check-codestyle
  extends: .check-codestyle

build:
  stage: build
  extends: .build-script

test:
  stage: test
  extends: .test-script
